networks:
  # Here we override the subnets in the hope that the internal QEMU VM's docker doesn't reassign the same ranges by default
  backplane:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "10.252.252.0/24"
  frontend:
    internal: false
    ipam:
      driver: default
      config:
        - subnet: "10.253.253.0/24"

services:
  squid:
    image: ghcr.io/tzarc/ephemeral-github-runner:latest-squid
    restart: always
    networks:
      - frontend
      - backplane
    environment:
      - "ALLOWED_DOMAINS_LIST=.pypi.org .pythonhosted.org .arm.com .docker.com .docker.io .github.com .githubapp.com .githubusercontent.com .blob.core.windows.net .actions.githubusercontent.com .pkg.github.com ghcr.io"

  runner-proxied:
    image: ghcr.io/tzarc/ephemeral-github-runner:latest
    restart: always
    devices:
      - "/dev/kvm:/dev/kvm"
    networks:
      - backplane
    depends_on:
      - squid
    environment:
      - "NUM_CPUS=${NUM_CPUS:-2}"
      - "MEMORY_ALLOC=${MEMORY_ALLOC:-4096}"
      - "NICE_VAL=19"
      - "GITHUB_REPOSITORY=${GITHUB_REPOSITORY:?Variable not set}" # should be in the format "owner/repo"
      - "GITHUB_TOKEN=${GITHUB_TOKEN:?Variable not set}" # Should be a fine-grained personal access token with "administration" permission on the repository above
      - "http_proxy=http://squid:3128" # Point at the squid instance above so that it has external access to the allowed domains
      - "https_proxy=http://squid:3128" # As above
