FROM alpine:latest

RUN apk update \
    && apk --no-cache add bash qemu-system-x86_64 qemu-img runit jq curl github-cli xz

COPY outer-container/support/entrypoint.sh /entrypoint.sh
COPY disk-image.qcow2.xz /disk-image.qcow2.xz

ENTRYPOINT ["/entrypoint.sh"]
