name: Build and push Docker image

on:
  push:
  release:
    types: [created]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build/Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine runner container tag names
        uses: actions/github-script@v6
        id: set-runner-tags
        with:
          result-encoding: string
          script: |
            if (context.ref.startsWith('refs/tags/v')) {
              return 'ghcr.io/' + context.repo.owner + '/' + context.repo.repo + ':latest' +
                    ' ghcr.io/' + context.repo.owner + '/' + context.repo.repo + ':' + context.ref.replace('refs/tags/v', '')
            } else {
              return 'ghcr.io/' + context.repo.owner + '/' + context.repo.repo + ':' + context.sha
            }

      - name: Determine squid container tag names
        uses: actions/github-script@v6
        id: set-squid-tags
        with:
          result-encoding: string
          script: |
            if (context.ref.startsWith('refs/tags/v')) {
              return 'ghcr.io/' + context.repo.owner + '/' + context.repo.repo + ':latest-squid' +
                    ' ghcr.io/' + context.repo.owner + '/' + context.repo.repo + ':' + context.ref.replace('refs/tags/v', '') + '-squid'
            } else {
              return 'ghcr.io/' + context.repo.owner + '/' + context.repo.repo + ':' + context.sha + '-squid'
            }

      - name: Show target tags
        run: |
          echo 'Runner tags:'
          for tag in ${{ steps.set-runner-tags.outputs.result }}; do
            echo $tag
          done
          echo 'Squid tags:'
          for tag in ${{ steps.set-squid-tags.outputs.result }}; do
            echo $tag
          done

      - name: Install prerequisites
        run: |
          sudo apt update \
            && sudo apt install -y xz-utils qemu-utils

      - name: Build containers
        run: |
          make container
          for tag in ${{ steps.set-runner-tags.outputs.result }}; do
            docker tag github-runner-vm:latest $tag
          done
          make squid-container
          for tag in ${{ steps.set-squid-tags.outputs.result }}; do
            docker tag github-runner-squid:latest $tag
          done

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          for tag in ${{ steps.set-runner-tags.outputs.result }}; do
            docker push $tag
          done
          for tag in ${{ steps.set-squid-tags.outputs.result }}; do
            docker push $tag
          done
