name: Build and push Docker image

on:
  push:
  release:
    types: [created]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine container tag names
        uses: actions/github-script@v6
        id: set-container-tags
        with:
          result-encoding: string
          script: |
            if (typeof(github.ref) !== 'undefined' && github.ref.startsWith('refs/tags/v')) {
              return 'ghrc.io/' + context.repo.owner + '/' + context.repo.repo + ':latest' +
                    ' ghrc.io/' + context.repo.owner + '/' + context.repo.repo + ':' + context.payload.release.tag_name.replace('v', '')
            } else {
              return 'ghrc.io/' + context.repo.owner + '/' + context.repo.repo + ':' + context.sha
            }

      - name: Build container
        run: |
          make container
          for tag in ${{ steps.set-container-tags.outputs.result }}; do
            docker tag github-runner-vm:latest $tag
          done

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to registry
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          for tag in ${{ steps.set-container-tags.outputs.result }}; do
            docker push $tag
          done
